#!/usr/bin/env bash

set -e -o pipefail
shopt -s dotglob lastpipe

if ! [ ${BASH_VERSINFO[0]} -ge 5 ]; then
   echo "⛔️ bash version found: $BASH_VERSION, these scripts require bash 5+"
   # beep
   tput bel
   echo "  I strongly urge you to upgrade bash to the latest version before using these scripts."
fi

if [ -z "$HOME" ]; then
   echo "⛔️ HOME environment variable is not set, cannot continue"
   echo "   Something is terribly wrong with your shell environment, sorry."
   exit 1
fi

cd "$(dirname "$0")" || exit 1

echo "🔗 Creating symlinks in \$HOME = $HOME"

for scriptfile in ./.*.sh; do

   script_base="$(basename "$scriptfile")"

   if [ -e ~/"$script_base" ]; then
      if [ -L ~/"$script_base" ]; then
         echo "⚠️ symlink for $script_base already exists, refreshing"
      else
         # bad, something else is here, skip this one
         echo "⚠⛔️️ $script_base already exists in HOME and is not a symlink! skipping"
         continue
      fi
   fi

   source="$PWD/$script_base"
   target="$HOME/$script_base"

   # declare -p source target
   ln -svf "$source" "$target"

done
